// 6과 문제 데이터
const UNIT6_DATA = {
   WORD_QUESTIONS: [
        { id: 'w6_1', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nkind", answer: ["종류"] },
        { id: 'w6_2', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nusually", answer: ["보통", "대개", "주로"] },
        { id: 'w6_3', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nsci-fi", answer: ["공상 과학의", "과학 소설적인"] },
        { id: 'w6_4', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nnovel", answer: ["소설"] },
        { id: 'w6_5', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nrecommend", answer: ["~을 추천하다", "추천하다"] },
        { id: 'w6_6', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nsoda", answer: ["탄산음료"] },
        { id: 'w6_7', type: 'text', title: "다음 단어의 뜻을 쓰시오.\ngive it a try", answer: ["시도하다", "한번 해 보다"] },
        { id: 'w6_8', type: 'text', title: "다음 단어의 뜻을 쓰시오.\ntry", answer: ["~을 해 보다", "해보다", "시도하다"] },
        { id: 'w6_9', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nfavorite", answer: ["가장 좋아하는", "가장 좋아하는 것"] },
        { id: 'w6_10', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nstrongly", answer: ["강하게", "강력하게"] },
        { id: 'w6_11', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nmagazine", answer: ["잡지"] },
        { id: 'w6_12', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nbe interested in", answer: ["관심이 있다", "흥미가 있다", "~에 관심이 있다", "~에 흥미가 있다"] },
        { id: 'w6_13', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nfind", answer: ["찾다", "찾아내다"] },
        { id: 'w6_14', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nteen", answer: ["십대", "십대 청소년"] },
        { id: 'w6_15', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nlook for", answer: ["~을 찾다", "찾다"] },
        { id: 'w6_16', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nfamous", answer: ["유명한"] },
        { id: 'w6_17', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nwell-known", answer: ["유명한", "잘 알려진"] },
        { id: 'w6_18', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nessay", answer: ["보고서", "에세이"] },
        { id: 'w6_19', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nthink about", answer: ["~에 대해 생각하다"] },
        { id: 'w6_20', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nactor", answer: ["배우"] },
        { id: 'w6_21', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nvolunteer", answer: ["자원봉사", "봉사"] },
        { id: 'w6_22', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nvolunteer work", answer: ["자원봉사 활동", "봉사 활동"] },
        { id: 'w6_23', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nespecially", answer: ["특히", "특별히"] },
        { id: 'w6_24', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nintroduce", answer: ["소개하다"] },
        { id: 'w6_25', type: 'text', title: "다음 단어의 뜻을 쓰시오.\npianist", answer: ["피아니스트"] },
        { id: 'w6_26', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nlose", answer: ["잃다", "~을 잃다"] },
        { id: 'w6_27', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nmove", answer: ["이사하다", "이주하다"] },
        { id: 'w6_28', type: 'text', title: "다음 단어의 뜻을 쓰시오.\ntouching", answer: ["감동적인", "감동을 주는"] },
        { id: 'w6_29', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nforeigner", answer: ["외국인"] },
        { id: 'w6_30', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nFebruary", answer: ["2월"] },
        { id: 'w6_31', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nspecial", answer: ["특별한"] },
        { id: 'w6_32', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nfavor", answer: ["호의", "부탁"] },
        { id: 'w6_33', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nask", answer: ["묻다", "요청하다", "부탁하다", "물어보다"] },
        { id: 'w6_34', type: 'text', title: "다음 단어의 뜻을 쓰시오.\ngather", answer: ["모이다", "모으다"] },
        { id: 'w6_35', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nindependence", answer: ["독립"] },
        { id: 'w6_36', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nindependent", answer: ["독립적인", "독립된", "독립한"] },
        { id: 'w6_37', type: 'text', title: "다음 단어의 뜻을 쓰시오.\ntake a picture of", answer: ["~의 사진을 찍다"] },
        { id: 'w6_38', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nevent", answer: ["사건", "사태"] },
        { id: 'w6_39', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nshare", answer: ["공유하다", "나누다"] },
        { id: 'w6_40', type: 'text', title: "다음 단어의 뜻을 쓰시오.\noutside", answer: ["밖에", "밖에서", "바깥에", "바깥에서"] },
        { id: 'w6_41', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nMarch", answer: ["3월"] },
        { id: 'w6_42', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nhide", answer: ["숨다"] },
        { id: 'w6_43', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nbuilding", answer: ["건물"] },
        { id: 'w6_44', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nunbelievable", answer: ["믿기지 않는", "믿기 힘들 정도의"] },
        { id: 'w6_45', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nhope", answer: ["바라다", "희망하다", "소망하다"] },
        { id: 'w6_46', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nlearn", answer: ["알게 되다", "배우다"] },
        { id: 'w6_47', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nthrough", answer: ["~을 통해", "통해", "통하여", "~을 통하여", "통해서"] },
        { id: 'w6_48', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nsound", answer: ["~하게 들리다", "들리다"] },
        { id: 'w6_49', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nsimilar to", answer: ["~와 비슷한"] },
        { id: 'w6_50', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nreal", answer: ["실제의", "진짜의"] },
        { id: 'w6_51', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nmeaning", answer: ["의미", "뜻"] },
        { id: 'w6_52', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nCanadian", answer: ["캐나다인", "캐나다 사람", "캐나다의"] },
        { id: 'w6_53', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nfirst", answer: ["최초로", "처음으로"] },
        { id: 'w6_54', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nmedicine", answer: ["의학"] },
        { id: 'w6_55', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nright away", answer: ["즉시", "곧바로"] },
        { id: 'w6_56', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nright", answer: ["권리"] },
        { id: 'w6_57', type: 'text', title: "다음 단어의 뜻을 쓰시오.\ncountry", answer: ["나라"] },
        { id: 'w6_58', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nmovement", answer: ["운동"] },
        { id: 'w6_59', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nshout", answer: ["소리치다", "외치다", "소리지르다"] },
        { id: 'w6_60', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nhistoric", answer: ["역사적인", "역사상 중요한"] },
        { id: 'w6_61', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nforeign", answer: ["외국의"] },
        { id: 'w6_62', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nfight", answer: ["투쟁", "분투"] },
        { id: 'w6_63', type: 'text', title: "다음 단어의 뜻을 쓰시오.\neven", answer: ["조차도", "심지어"] },
        { id: 'w6_64', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nterrible", answer: ["끔찍한", "참혹한"] },
        { id: 'w6_65', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nsituation", answer: ["상황"] },
        { id: 'w6_66', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nunder the watchful eye of", answer: ["~의 감사 하에", "주의 깊게 지켜보는 가운데"] },
        { id: 'w6_67', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nwatchful", answer: ["감시하는", "주의 깊게 지켜보는"] },
        { id: 'w6_68', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nreturn", answer: ["돌아오다", "돌아가다"] },
        { id: 'w6_69', type: 'text', title: "다음 단어의 뜻을 쓰시오.\ninvitation", answer: ["초대", "초청"] },
        { id: 'w6_70', type: 'text', title: "다음 단어의 뜻을 쓰시오.\ndie", answer: ["죽다"] },
        { id: 'w6_71', type: 'text', title: "다음 단어의 뜻을 쓰시오.\npoor", answer: ["가난한", "빈곤한"] },
        { id: 'w6_72', type: 'text', title: "다음 단어의 뜻을 쓰시오.\npoverty", answer: ["빈곤", "가난"] },
        { id: 'w6_73', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nnational", answer: ["국가적인"] },
        { id: 'w6_74', type: 'text', title: "다음 단어의 뜻을 쓰시오.\ncemetery", answer: ["묘지", "공동 묘지"] },
        { id: 'w6_75', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nbury", answer: ["매장하다", "묻다"] },
        { id: 'w6_76', type: 'text', title: "다음 단어의 뜻을 쓰시오.\nrest", answer: ["나머지"] },
        { id: 'w6_77', type: 'text', title: "다음 단어의 뜻을 쓰시오.\ngovernment", answer: ["정부"] },
        { id: 'w6_78', type: 'text', title: "다음 단어의 뜻을 쓰시오.\narticle", answer: ["기사"] }
    ],
    VOCAB: [],
    DIALOGUE: [],
    GRAMMAR: [],
    READING: []
};
